## ***Linear-Algebra***

## Topics

- Vectors and Vector Application
- Matrices and its applications
- orthogonal Matrices and QR decomposition
- Row Reduction and LU Decomposition
- General Linear model and Least square method and least square method application
- Eigendecomposition
- SVD and its application

### *Vector and Vector Applications*

In [2]:
import numpy as np
import matplotlib.pyplot as plt
import sympy as sp

*In programming Vector in "List" of number*
*Eg-*

```python
    V=[1,2,3,4]    
```
*V is a vector* 

Note-Every Vector have 2 things as they are list, these are **dimesionality** and **Orientation**

#### Dimesionality is number of numbers in vector (eg in above vector V we have dimesionality as 4 as there are 4 numbers in V) we can find this dimesionality using len(vector)

#### Orientation is how vector is arranged in space but in programming its either ROW or COLUMN orientation

In [16]:
# lets define some Vector but we will use numpy as it prodive more funcationlity and written in C so its going to be fast

v1=np.array([1,2,3])# np.array always expect a list as input 
print(v1,type(v1))

print('''NOTE: vector V1 is dimensionless which means it can neither be a row vector nor column vector''')
print(v1.ndim)
print(f"{v1.shape}, This shows us it is dimensionless")

[1 2 3] <class 'numpy.ndarray'>
NOTE: vector V1 is dimensionless which means it can neither be a row vector nor column vector
1
(3,), This shows us it is dimensionless


In [15]:
#Vector with dimensions (row,column) are defined as :

v1_row=np.array([[1,2,3]])
print(f"{v1_row}<- Vector\n{v1_row.ndim}<-Dimensions it have \n{v1_row.shape}<-Shape of the vector")

v1_column=np.array([[1],[2],[3]])
print(f"\n\n{v1_column}<- Vector\n{v1_column.ndim}<-Dimensions it have \n{v1_column.shape}<-Shape of the vector")

[[1 2 3]]<- Vector
2<-Dimensions it have 
(1, 3)<-Shape of the vector


[[1]
 [2]
 [3]]<- Vector
2<-Dimensions it have 
(3, 1)<-Shape of the vector


*The Dimesionality in python is something different it is number of element in vector.shape*
#### if a shape of vector v1 is given as (3,4,5) its dimensionality is 3.
#### another shape of vector is (3,) its dimesionality is 1.
#### at last if (1,3) its 2-dimensional 

## Operations on Vectors 

In [19]:
#addition

v1=np.array([1,2,3]) # dimensionless vector 
v2=np.array([[1,2,3]]) # row Vector 
v3=np.array([[1],[2],[3]]) # column vector 

v4=np.array([[1,2]]) # row vector with different shape 
v5=np.array([[1],[2]])# column vector with different shape

print(f"{v1+v2}\n")
print(f"{v1+v3}\n")
print(f"{v2+v3}\n")
print(f"{v2+v4}\n")


[[2 4 6]]

[[2 3 4]
 [3 4 5]
 [4 5 6]]

[[2 3 4]
 [3 4 5]
 [4 5 6]]



ValueError: operands could not be broadcast together with shapes (1,3) (1,2) 

## So from above we understood that in order for addition to occur we need to have same shape and orientation does'nt matter i.e number in shape should be same i.e if a vector have shape (1,7) other vector should either have shape (7,1) or (1,7) for addition to occur 
## for shape (a,b) and (b,a) addition can occure as python uses  broadcasting method to 
## A dimensionaless vector is treated as row vector for addition ?!
## similary substraction is performed in 